//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV_client.Server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Email", Namespace="http://schemas.datacontract.org/2004/07/DV_server")]
    [System.SerializableAttribute()]
    public partial class Email : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IDV_server")]
    public interface IDV_server {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDV_server/GetEmails", ReplyAction="http://tempuri.org/IDV_server/GetEmailsResponse")]
        DV_client.Server.Email[] GetEmails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDV_server/GetEmails", ReplyAction="http://tempuri.org/IDV_server/GetEmailsResponse")]
        System.Threading.Tasks.Task<DV_client.Server.Email[]> GetEmailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDV_server/saveEmail", ReplyAction="http://tempuri.org/IDV_server/saveEmailResponse")]
        bool saveEmail(DV_client.Server.Email email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDV_server/saveEmail", ReplyAction="http://tempuri.org/IDV_server/saveEmailResponse")]
        System.Threading.Tasks.Task<bool> saveEmailAsync(DV_client.Server.Email email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDV_serverChannel : DV_client.Server.IDV_server, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DV_serverClient : System.ServiceModel.ClientBase<DV_client.Server.IDV_server>, DV_client.Server.IDV_server {
        
        public DV_serverClient() {
        }
        
        public DV_serverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DV_serverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DV_serverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DV_serverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DV_client.Server.Email[] GetEmails() {
            return base.Channel.GetEmails();
        }
        
        public System.Threading.Tasks.Task<DV_client.Server.Email[]> GetEmailsAsync() {
            return base.Channel.GetEmailsAsync();
        }
        
        public bool saveEmail(DV_client.Server.Email email) {
            return base.Channel.saveEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> saveEmailAsync(DV_client.Server.Email email) {
            return base.Channel.saveEmailAsync(email);
        }
    }
}
